//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutsWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> EventStartDateTime { get; set; }
        public Nullable<System.DateTime> EventEndDateTime { get; set; }
        public string EventCreatedBy { get; set; }
        public Nullable<System.DateTime> EventCreatedDate { get; set; }
        public string EventModifiedBy { get; set; }
        public Nullable<System.DateTime> EventModifiedDate { get; set; }
    }
}
